FROM ros:humble-ros-core
RUN apt-get update && apt-get install -y build-essential cmake python3-colcon-common-extensions libfftw3-dev
WORKDIR /ws
COPY ros2_ws /ws/ros2_ws
WORKDIR /ws/ros2_ws
RUN . /opt/ros/humble/setup.sh && colcon build --symlink-install
CMD ["/bin/bash"]